#Dockerfile

from python:3.8-buster

WORKDIR /app

WORKDIR /run

RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential gcc libsndfile1 

RUN apt-get install -y libasound-dev -y

RUN apt-get install libportaudio2 -y

ADD requirements.txt .

RUN pip install -r requirements.txt

ADD live_audio_stream.py .

WORKDIR /app

CMD ["python","/run/live_audio_stream.py"]